import fs from 'fs';
const cnToEn = [
  ['首页','Home'],['分类','Categories'],['关于我们','About Us'],['联系我们','Contact'],
  ['博客','Blog'],['开始阅读','Read Reviews'],['返回顶部','Back to Top'],
  ['查看全部文章','View All Articles'],['← 查看全部文章','← View All Articles'],
  ['分钟阅读','min read'],['阅读更多','Read More'],['查看更多评测','More Reviews'],
  ['浏览分类','Browse Categories'],['查看精选','View Picks'],
  ['探索世界顶级产品，为品味卓越的生活方式甄选经典之作。','Curated reviews and expert insights for discerning lifestyles.'],
  ['团队故事','Our Team'],['编辑流程','Editorial Process'],['使命愿景','Our Mission'],
  ['快速链接','Quick Links'],['法律声明','Legal'],
  ['隐私政策','Privacy Policy'],['服务条款','Terms of Service'],['联盟营销披露','Affiliate Disclosure'],
  ['作为亚马逊联盟会员，我们通过合格购买赚取佣金。所有推荐均为独立且公正的。','As an Amazon Associate we earn from qualifying purchases. All reviews are independent and unbiased.'],
  ['TRUSTED REVIEWS SINCE 2026','TRUSTED REVIEWS SINCE 2026'],
  ['探索世界<br/>顶级产品','Discover the World'"'s Best Products'],
  ['精选评论，专家见解，为品味卓越的生活方式甄选的经典之作。','Curated reviews, expert insights, and hand-picked picks for discerning lifestyles.'],
  ['按类别浏览','Browse by Category'],
  ['从五大品类中探索精心甄选的优质产品','Explore curated quality products across five categories'],
  ['款产品','Products'],['款产品评测','Product Reviews'],
  ['家居与厨房','Home & Kitchen'],['健身与健康','Fitness & Health'],
  ['美容与个人护理','Beauty & Personal Care'],['智能家居','Smart Home'],
  ['户外与旅行','Outdoor & Travel'],
  ['编辑精选','Editor'"'s Picks'],['本月最佳推荐','Top Picks This Month'],
  ['阅读全文','Read Full Review'],['阅读评论','Read Review'],
  ['加入超过5万名眼光独到的购物者','Join 50,000+ Discerning Shoppers'],
  ['每周精选推荐，专家深度评测，第一时间获取顶级产品资讯。','Weekly curated picks, expert deep-dive reviews, and first-access to top product insights.'],
  ['请输入您的邮箱','Enter your email address'],['订阅周报','Subscribe'],
  ['我们尊重您的隐私，绝不会发送垃圾邮件。','We respect your privacy. No spam, ever.'],
  ['产品评测博客','Product Reviews'],
  ['专家深度评测，真实用户体验，帮助您做出明智的购买决策。','Expert reviews, real user experiences, helping you make smart buying decisions.'],
  ['LuxeRank 成立于2026年，致力于为全球消费者提供最专业、最客观的产品评测服务。我们相信，每一个精心挑选的产品，都能为您的生活增添品质与格调。','Founded in 2026, LuxeRank is dedicated to providing the most professional and objective product reviews for consumers worldwide. We believe every carefully selected product can add quality and style to your life.'],
  ['我们的使命','Our Mission'],
  ['在信息爆炸的时代，消费者面临着前所未有的选择困难。我们的产品评测团队由经验丰富的行业专家组成，通过严谨的测试流程，为您提供真正有价值的购买建议。我们承诺每篇评测都基于真实用户体验，不受任何品牌影响。','In an era of information overload, consumers face unprecedented choice paralysis. Our review team consists of experienced industry experts who provide genuinely valuable purchasing advice through rigorous testing. We commit that every review is based on real user experiences, free from brand influence.'],
  ['编辑流程','Editorial Process'],
  ['我们的评测流程包括：产品调研（3天）→ 实地测试（7天）→ 对比分析（2天）→ 内容撰写（3天）→ 专家审核（1天）。每篇评测至少经过3轮审核，确保信息的准确性和客观性。所有测试产品均通过正规渠道购买，不接受品牌方免费提供。','Our review process includes: Product Research (3 days) → Field Testing (7 days) → Comparative Analysis (2 days) → Content Writing (3 days) → Expert Review (1 day). Each review undergoes at least 3 rounds of editing for accuracy and objectivity. All test products are purchased through legitimate channels; we never accept free products from brands.'],
  ['产品测试','Products Tested'],['订阅用户','Subscribers'],['独立评测','Independent Reviews'],
  ['我们是一支充满激情的团队，每一位成员都是产品爱好者。从厨房小家电到智能穿戴设备，从健身器材到美妆工具，我们用专业的视角为您甄选每一件值得购买的产品。','We are a passionate team, every member is a product enthusiast. From kitchen appliances to smart wearables, from fitness equipment to beauty tools, we use professional perspectives to curate every product worth buying.'],
  ['有任何问题或建议？我们期待与您的交流。','Have questions or suggestions? We would love to hear from you.'],
  ['发送消息','Send Message'],['姓名','Name'],['请输入您的姓名','Enter your name'],
  ['邮箱','Email'],['请输入您的邮箱','Enter your email'],
  ['主题','Subject'],['合作咨询','Partnership Inquiry'],['内容反馈','Content Feedback'],
  ['技术支持','Tech Support'],['其他','Other'],
  ['留言内容','Message'],['请输入您的留言内容...','Type your message...'],
  ['提交消息','Send Message'],['联系方式','Contact Info'],
  ['地址','Address'],['美国加利福尼亚州洛杉矶','Los Angeles, California, USA'],
  ['工作时间','Business Hours'],['周一至周五','Monday - Friday'],
  ['9:00 AM - 6:00 PM (PST)','9:00 AM - 6:00 PM (PST)'],
  ['周末','Weekends'],['休息','Closed'],
  ['合作伙伴','Partnerships'],
  ['如果您是我们的潜在合作伙伴，欢迎通过以下方式联系我们：','If you are a potential partner, feel free to reach out:'],
  ['隐私政策','Privacy Policy'],['最后更新：2026年1月1日','Last updated: January 1, 2026'],
  ['引言','Introduction'],
  ['LuxeRank（以下简称"我们"或"本网站"）尊重您的隐私，致力于保护您的个人信息。本隐私政策说明了我们如何收集、使用、存储和保护您的个人信息，以及您享有的权利。','LuxeRank ("we" or "our") respects your privacy and is committed to protecting your personal information. This privacy policy explains how we collect, use, store, and protect your personal information, and the rights you enjoy.'],
  ['信息收集','Information We Collect'],
  ['我们可能收集以下类型的信息：','We may collect the following types of information:'],
  ['个人信息：','Personal Information:'],
  ['当您订阅我们的通讯、联系我们或参与调查时，我们可能会收集您的姓名、电子邮件地址等信息。','When you subscribe to our newsletter, contact us, or participate in surveys, we may collect your name, email address, and other information.'],
  ['技术信息：','Technical Information:'],
  ['我们使用 cookies 和其他追踪技术收集您的浏览数据，包括 IP 地址、浏览器类型、访问时间等。','We use cookies and other tracking technologies to collect your browsing data, including IP address, browser type, access time, and more.'],
  ['联盟营销数据：','Affiliate Marketing Data:'],
  ['我们使用第三方分析工具跟踪您的购买行为，以便计算佣金。','We use third-party analytics tools to track your purchasing behavior for commission calculations.'],
  ['信息使用','How We Use Your Information'],
  ['我们使用收集的信息用于以下目的：','We use collected information for the following purposes:'],
  ['提供和改进我们的服务','Provide and improve our services'],
  ['发送新闻通讯和产品推荐','Send newsletters and product recommendations'],
  ['响应您的查询和请求','Respond to your inquiries and requests'],
  ['分析网站使用情况以优化用户体验','Analyze website usage to optimize user experience'],
  ['遵守法律法规要求','Comply with legal obligations'],
  ['信息共享','Information Sharing'],
  ['我们不会出售您的个人信息。我们可能与以下类型的第三方共享信息：','We will not sell your personal information. We may share information with the following third parties:'],
  ['联盟营销合作伙伴（如亚马逊联盟）','Affiliate marketing partners (e.g., Amazon Associates)'],
  ['网站分析服务提供商','Website analytics service providers'],
  ['邮件营销服务提供商','Email marketing service providers'],
  ['您的权利','Your Rights'],
  ['根据 GDPR 和 CCPA 等隐私法规，您享有以下权利：','Under privacy regulations such as GDPR and CCPA, you have the following rights:'],
  ['访问您保存在我们系统中的个人信息','Access personal information stored in our system'],
  ['要求更正不准确的个人信息','Request correction of inaccurate personal information'],
  ['要求删除您的个人信息','Request deletion of your personal information'],
  ['反对处理您的个人信息','Object to processing of your personal information'],
  ['数据可携权','Data portability right'],
  ['如果您对本隐私政策有任何疑问，请通过 contact@luxerrank.com 联系我们。','If you have any questions about this privacy policy, please contact us at contact@luxerrank.com.'],
  ['服务条款','Terms of Service'],
  ['接受条款','Acceptance of Terms'],
  ['访问和使用 LuxeRank 网站即表示您同意遵守本服务条款。如果您不同意本条款的任何部分，请勿使用本网站。','Accessing and using the LuxeRank website means you agree to be bound by these terms of service. If you do not agree with any part of these terms, please do not use this website.'],
  ['内容使用','Content Usage'],
  ['本网站上的所有内容（包括但不限于文字、图片、设计、图标）均受版权保护。未经书面许可，您不得复制、修改、传播或创建衍生作品。','All content on this website (including but not limited to text, images, designs, and icons) is protected by copyright. You may not reproduce, modify, distribute, or create derivative works without written permission.'],
  ['免责声明','Disclaimer'],
  ['我们努力确保网站内容的准确性和时效性，但不保证所有信息的完整性或准确性。您基于网站内容做出的任何决策均由您自行承担风险。','We strive to ensure the accuracy and timeliness of website content, but do not guarantee the completeness or accuracy of all information. Any decisions made based on website content are at your own risk.'],
  ['责任限制','Limitation of Liability'],
  ['在法律允许的最大范围内，LuxeRank 不对任何间接、附带、特殊或后果性损害承担责任。','To the fullest extent permitted by law, LuxeRank is not liable for any indirect, incidental, special, or consequential damages.'],
  ['变更通知','Changes to Terms'],
  ['我们保留随时修改本条款的权利。重大变更将通过网站公告通知用户。','We reserve the right to modify these terms at any time. Material changes will be notified to users through website announcements.'],
  ['联盟营销披露声明','Affiliate Disclosure'],
  ['重要声明：','Important Statement:'],
  ['作为亚马逊联盟会员（Amazon Associate），我们通过符合条件的购买赚取佣金。','As an Amazon Associate, we earn from qualifying purchases.'],
  ['这意味着当您通过本网站的链接购买产品时，我们可能会获得少量佣金。这不会增加您的购买成本，但有助于支持我们继续制作高质量的产品评测内容。','This means when you purchase products through links on this website, we may earn a small commission. This does not increase your purchase cost but helps support our continued production of high-quality product review content.'],
  ['我们的立场','Our Stance'],
  ['所有推荐均为独立且公正的。我们的评测团队独立购买所有测试产品，不接受品牌方免费提供产品或报酬来影响评测结果。我们的评分和推荐完全基于产品的实际表现和用户价值。','All recommendations are independent and unbiased. Our review team independently purchases all test products and does not accept free products or compensation from brands to influence review results. Our ratings and recommendations are based solely on actual product performance and user value.'],
  [' FTC 合规声明',' FTC Compliance Statement'],
  ['根据美国联邦贸易委员会（FTC）的要求，我们特此披露：本网站包含联盟营销链接。您通过点击这些链接进行的购买可能会使我们获得佣金。','In compliance with the Federal Trade Commission (FTC) requirement, we disclose that this website contains affiliate marketing links. Purchases made through these links may earn us a commission.'],
  ['其他联盟计划','Other Affiliate Programs'],
  ['除了亚马逊联盟计划外，我们可能还参与其他联盟营销计划，包括但不限于：','In addition to the Amazon Associates program, we may participate in other affiliate marketing programs, including but not limited to:'],
  ['Best Buy 联盟计划','Best Buy Affiliate Program'],
  ['Walmart 联盟计划','Walmart Affiliate Program'],
  ['Target 联盟计划','Target Affiliate Program'],
  ['特定品牌的直接联盟计划','Direct affiliate programs from specific brands'],
  ['如何识别联盟链接','How to Identify Affiliate Links'],
  ['我们的联盟链接通常会在按钮或文本链接中显示"在亚马逊上查看价格"等字样。当您被重定向到第三方网站完成购买时，即为联盟链接。','Our affiliate links typically display text like "Check Price on Amazon" in buttons or text links. When you are redirected to a third-party website to complete a purchase, it is an affiliate link.'],
  ['页面未找到','Page Not Found'],
  ['抱歉，您访问的页面不存在','Sorry, the page you are looking for does not exist'],
  ['返回首页','Back to Home'],
];
function translate(text) {
  let r = text;
  [...cnToEn].sort((a,b) => b[0].length - a[0].length).forEach(([cn,en]) => { r = r.split(cn).join(en); });
  r = r.replace(/(\d{4})年(\d+)月(\d+)日/g,' , ');
  return r;
}
const base='D:/下载文件/指纹浏览器/网站（豪华）/luxerank';
const targetFiles=[
  'src/components/Header.astro','src/components/Footer.astro',
  'src/pages/index.astro','src/pages/about.astro','src/pages/contact.astro',
  'src/pages/categories/index.astro','src/pages/blog/index.astro',
  'src/pages/privacy.astro','src/pages/terms.astro','src/pages/affiliate-disclosure.astro','src/pages/404.astro',
];
const blogDir=base+'/src/pages/blog/';
const blogFiles=fs.readdirSync(blogDir).filter(f=>f.endsWith('.astro')).map(f=>blogDir+f);
const allFiles=[...targetFiles,...blogFiles];
console.log('Translating',allFiles.length,'files...');
for(const file of allFiles){
  let c=fs.readFileSync(file,'utf8');
  const before=c;
  c=translate(c);
  if(c!==before){fs.writeFileSync(file,c,'utf8');console.log('  '+file.split('/').pop());}
}
console.log('Done!');
